name = "vidninja-hls-proxy"
compatibility_date = "2025-08-01"
main = "src/index.ts"

# Environment variables
[vars]
MAX_SESSION_AGE = "3600000" # 1 hour in ms
CORS_ORIGINS = "*"         # Set specific domains if needed

# KV namespace bindings
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-production-namespace-id"

[[kv_namespaces]]
binding = "SESSIONS"
preview_id = "your-preview-namespace-id"

# Optional: Define routes for production
[[routes]]
pattern = "vidninja.pro/cdn-hls1/*"
custom_domain = true
